Feat/invite code
AlibudaLab/atomic-habit-builder pull request #209
Opened 2024-09-25 08:02 UTC by antoncoding

2024-09-25 15:20 UTC, Ankarrr requested changes
主要針對 referral code 的 db，我認爲目前問題是：
1. 無法保證 code 是 unique
2. referral system 通常對於 code 會有功能像是否過期、紀錄使用次數等，在目前設計下較難實現，可擴充性低

我的建議是：
1. 增加一個 db table 專門儲存 code
2. 在新增 code 時先檢查在 table 中是否存在
3. 之後可以增加額外欄位像是使用次數、active flag 等
4. [optional] 把 invitedArray 也儲存在這個 table

2024-09-25 15:53 UTC, antoncoding commented
## New DB layout
![Screenshot 2024-09-25 at 23 52 58](https://github.com/user-attachments/assets/b791e97b-2402-4407-b902-9fa14080a268)

2024-09-25 17:21 UTC, Ankarrr requested changes

2024-09-25 17:21 UTC, Ankarrr commented on web/app/api/user/referral/route.ts
> +    }
這看起來讓人擔心 XD 

可能會 infinite loop，雖然可能性不高

建議增加一個 retry threshold e.g. 3 次

2024-09-27 00:57 UTC, Ankarrr approved these changes

2024-09-27 16:23 UTC, merged